### ISSUE TITLE
Method says it sets the green theme, but still gets a parameter with the name

### ISSUE THREAD

**Issue by adrianpawlik** [programira/angular-chuck#4]
https://github.com/programira/angular-chuck/blob/076839f49783dad160d94e2f10803fe6283ab098/src/app/shared/services/header.service.ts#L12

**Comment by programira** [comment]
Added changes in 
https://github.com/programira/angular-chuck/pull/10/commits/b8af79a3c86845356167b06a0d3165a88dedf74d
