### ISSUE TITLE
What is the purpose of the CategoriesPayload class?

### ISSUE THREAD

**Issue by adrianpawlik** [programira/angular-chuck#7]
https://github.com/programira/angular-chuck/blob/076839f49783dad160d94e2f10803fe6283ab098/src/app/shared/models/categories.ts#L1

It does not introduce any custom logic, it's just an array of the Category.

**Comment by programira** [comment]
Added changes in 
https://github.com/programira/angular-chuck/pull/10/commits/5eda79ce66bd9da3f27da65d82f5db0f3fe4e469
